import UserIcon from '@/assets/icons/1.svg'
import SearchIcon from '@/assets/icons/2.svg'
import WishlistIcon from '@/assets/icons/3.svg'
import CartIcon from '@/assets/icons/4.svg'
import cupIcon from '@/assets/icons/10.svg'
import accumulationIcon from '@/assets/icons/11.svg'
import giftIcon from '@/assets/icons/12.svg'
import adviseIcon from '@/assets/icons/13.svg'
import Logo from '@/assets/logo.svg'
export { UserIcon, SearchIcon, WishlistIcon, CartIcon, Logo, cupIcon, accumulationIcon, giftIcon, adviseIcon}
